baseurl = "/"
languageCode = "en-gb"
footnoteReturnLinkContents = "â†©"

title = "Emanuela Campanella Fashion photographer"

disableKinds = ["RSS", "taxonomyTerm"]

[params]
  AuthorName = "Emanuela Campanella"
  Subtitle = "Fashion and Editorial photographer"
  
[permalinks]
  categories = "/:title/"
  portfolio = "/:slug/"